import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  fadeIn: {
    opacity: 0,
  },
  fill: {
    // backgroundSize: "0% 100%",
  },
  edit: {
    borderRadius: 10,
    height: 90,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    color: "#fff",
    fontSize: 18,
    flexGrow: 0,
    flexShrink: 1,
    padding: 10,
    margin: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  inner: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    flexGrow: 1,
    padding: 16,
    paddingVertical: 16,
  },
  outer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: 'stretch',
  },
  title: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-end",
    position: "relative",
    fontSize: 24,
    fontFamily: "PlayFairDisplayRegular",
    // alignItems: 'start',
  },
  approveBlock: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    padding: 0,
    margin: 0,
    columnGap: 10,
  },
  lastUpdated: {
    fontWeight: "bold",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 20,
    padding: 5,
    paddingLeft: 12,
    fontSize: 12,
    color: "#eee",
  },
  approveIcon: {
    opacity: 0.8,
    backgroundColor: "#214834",
    height: 40,
    width: 40,
    borderRadius: 100,
    display: "none",
    justifyContent: "center",
    alignItems: "center",
    // boxShadow: "inset 3px 3px 0px rgba(3, 3, 3, 3)",
  },
  approveIconVisible: {
    display: "flex",
  },
  copy: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  numbersCopy: {
    /* Empty style */
  },
  numbers: {
    fontSize: 24,
    color: "#600404",
    fontFamily: "BigBlueTermPlus Nerd Font",
    fontWeight: "900",
  },
  doneForDay: {
    // touchAction: 1,
    backgroundColor: "#ebc155",
    // backgroundImage: "linear-gradient(to right, #f0c863, 30%, #c6a44e)",
    borderWidth: 2,
    borderColor: "#c6a44e",
    color: "#222",
  },
  card: {
    backgroundColor: "#c1cae1",
    borderRadius: 10,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    borderColor: "#333",
    borderWidth: 3,
    overflow: "hidden",
    marginBottom: 16,
    // borderColor: '#333',
  },
  heading: {
    fontSize: 26,
    fontWeight: "900",
    marginBottom: 5,
    width: "100%",
    textAlign: "left",
    borderBottomWidth: 1.5,
    borderBottomColor: "#222",
  },
  editButtons: {
    display: "flex",
    flexDirection: "row",
    marginTop: -2,
    columnGap: 6,
    justifyContent: "flex-end",
  },
});
