import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  fadeIn: {
    opacity: 0,
  },
  fill: {
    // backgroundSize: "0% 100%",
  },
  edit: {
    borderRadius: 10,
    height: 90,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    color: "#fff",
    fontSize: 18,
    flexGrow: 0,
    flexShrink: 1,
    padding: 10,
    margin: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  inner: {
    display: "flex",
    flexDirection: "column",
    // width: 'fill-content',
    width: "100%",
    flexGrow: 1,
    padding: 10,
    paddingVertical: 16,
    // backgroundImage:"linear-gradient(to right, #697eb48a, 30%, #51596d, 95%, #c1cae1)",
    // backgroundRepeat: "no-repeat",
    // backgroundSize: "0% 100%",
  },
  innerFill: {
    // backgroundImage: "linear-gradient(to right, #697eb48a, 30%, #51596d, 95%, #c1cae1)",
    // backgroundSize: "110% 100%",
    // animation: 'fill 1.7s',
    // animationDuration: "1.7s",
    // animationFillMode: "fill",
  },
  outer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: 'stretch',
  },
  title: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    position: "relative",
    // alignItems: 'start',
  },
  approveBlock: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    padding: 0,
    margin: 0,
    columnGap: 10,
  },
  lastUpdated: {
    fontWeight: "bold",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 20,
    padding: 5,
    paddingLeft: 12,
    fontSize: 12,
    color: "#eee",
  },
  approveIcon: {
    opacity: 0.8,
    backgroundColor: "#214834",
    height: 40,
    width: 40,
    borderRadius: 100,
    display: "none",
    justifyContent: "center",
    alignItems: "center",
    // boxShadow: "inset 3px 3px 0px rgba(3, 3, 3, 3)",
  },
  approveIconVisible: {
    display: "flex",
  },
  copy: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  numbersCopy: {
    /* Empty style */
  },
  numbers: {
    fontSize: 24,
    color: "#600404",
    fontFamily: "BigBlueTermPlus Nerd Font",
  },
  doneForDay: {
    // touchAction: 1,
    backgroundColor: "#ebc155",
    // backgroundImage: "linear-gradient(to right, #f0c863, 30%, #c6a44e)",
    borderWidth: 2,
    borderColor: "#c6a44e",
    color: "#222",
  },
  card: {
    backgroundColor: "#c1cae1",
    borderRadius: 5,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    // borderWidth: 4,
    borderColor: "#c5cfe8",
    // animationDuration: "650ms",
    // animationFillMode: "forwards",
    // animationName: "fade-in",
    overflow: "hidden",
  },
  heading: {
    marginBottom: 45,
    fontWeight: 400,
  },
});
