import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  addModal: {
    backgroundColor: "#413952",
    height: "100%",
    marginTop: 70,
    marginHorizontal: 5,
    borderRadius: 20,
    color: "#fff",
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  button: {
    borderRadius: 0,
    textTransform: "uppercase",
    padding: 10,
    width: 100,
    display: "flex",
  },
  buttonWrapper: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-around",
    columnGap: 0,
  },
  textInput: {
    display: "flex",
    flexDirection: "column",
    color: "#eee",
    marginBottom: 1,
    textTransform: "capitalize",
  },
  frequency: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 0,
    marginVertical: 0,
    padding: 0,
    width: "100%",
    height: 60,
    justifyContent: "center",
  },
  everydayButton: {
    marginTop: 0,
    paddingTop: 0,
  },
  heading: {
    textAlign: "center",
    width: "100%",
    color: "#fff",
    paddingVertical: 5,
    fontSize: 20,
  },
  textWrapper: {
    color: "#fff",
    fontSize: 18,
  },
  checkbox: {
    // font: "inherit",
    color: "currentColor",
    width: 25,
    height: 25,
    borderRadius: 0.15,
    transform: [{ translateY: -0.075 }],
  },
  buttonStyles: {
    width: "100%",
    // border: 0,
    backgroundColor: "#222",
    color: "#ccc",
    padding: 0.5,
    textTransform: "uppercase",
    fontSize: 16,
    fontWeight: 600,
  },
});
