import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  addModal: {
    backgroundColor: "#fff",
    height: "100%",
    marginTop: 70,
    marginHorizontal: 5,
    borderRadius: 20,
    color: "#222",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderColor: "#222",
    borderWidth: 4,
    borderStyle: "solid",
    boxShadow: "10px -5px 0px #222",
    display: "flex",
    flexDirection: "column",
  },
  button: {
    borderRadius: 0,
    textTransform: "uppercase",
    padding: 10,
    width: 100,
    display: "flex",
  },
  buttonWrapper: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-around",
    columnGap: 0,
  },
  textInput: {
    display: "flex",
    flexDirection: "column",
    color: "#222",
    marginBottom: 10,
    textTransform: "capitalize",
    borderColor: "#222",
    borderWidth: 2,
    borderRadius: 8,
  },
  frequency: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 0,
    marginVertical: 0,
    padding: 0,
    width: "100%",
    height: 180,
    justifyContent: "center",
    columnGap: 15,
    rowGap: 15,
  },
  everydayButton: {
    marginTop: 0,
    paddingTop: 0,
  },
  heading: {
    textAlign: "center",
    width: "100%",
    color: "#222",
    paddingVertical: 5,
    fontSize: 34,
    fontFamily: "PlayfairDisplay_800ExtraBold",
    marginBottom: 20,
  },
  textWrapper: {
    color: "#222",
    fontSize: 18,
    marginBottom: 20,
  },
  checkbox: {
    color: "currentColor",
    width: 25,
    height: 25,
    borderRadius: 0.15,
    transform: [{ translateY: -0.075 }],
  },
  buttonStyles: {
    width: "100%",
    backgroundColor: "#222",
    color: "#ccc",
    padding: 0.5,
    textTransform: "uppercase",
    fontSize: 16,
    fontWeight: 600,
  },
  FreqBox: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 0,
    marginVertical: 0,
    padding: 0,
    width: 68,
    height: 68,
    borderColor: "#222",
    borderWidth: 2,
    justifyContent: "center",
  },
  freqBoxTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "#222",
    width: 68,
    fontFamily: "PlayfairDisplay_800ExtraBold",
    textAlign: "center",
    borderBottomColor: "#222",
    borderBottomWidth: 1,
  },
});
